spring:
  thymeleaf:
    cache: false
    check-template-location: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 828269246467-p5e97ndekapgfmrq5a0ai6fe5r35bv63.apps.googleusercontent.com
            client-secret: xRNiaD5ijmsuvUIBTuhbzsio
server:
  port: 8080